### ISSUE TITLE
Hello, which model should be used for the final version in your code?

### ISSUE THREAD

**Issue by xiaobingbuhuitou** [TviNet/NetSolP-1.0#3]
In the NetSolIP paper, various models are mentioned, but in the code, I only observed esm1-t12 and esm1b-650. Does this mean that NetSolIP fine-tuned these two models separately and tested them on all datasets? Have a good day!

**Comment by teevee112** [comment]
Hi,

While we have tested various other models for benchmarking, we only provide the NetSolP models in this code. NetSolP is an ensemble of ESM1b-650 fine-tuned and quantized.
